# Generated by Django 4.0.1 on 2022-01-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
