# Generated by Django 4.0.1 on 2022-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.BooleanField(),
        ),
    ]
