# Generated by Django 4.0.1 on 2022-01-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('IR', 'In Review'), ('A', 'Accepted')], default='IR', max_length=2),
        ),
    ]
