# Generated by Django 4.0.1 on 2022-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(),
        ),
    ]
