# Generated by Django 4.0.1 on 2022-01-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
